apps/detector/models.py
from datetime import datetime

from apps.app import db

class UserImage(db.Model):
    __tablename__ = "user_images"
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String, db.ForeignKey("users.id"))
    image_path = db.Column(db.String)
    is_detected = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

class UserImageTag(db.Model):
    __tablename__ = "user_image_tags"
    id = db.Column(db.Integer, primary_key=True)
    user_image_id = db.Column(db.Integer, db.ForeignKey("user_images.id"))
    tag_name = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

apps/detector/forms.py
from flask_wtf.file import FileAllowed, FileField, FileRequired
from flask_wtf.form import FlaskForm
from wtforms import SubmitField

class UploadImageForm(FlaskForm):
    image = FileField(
        validators = [
            FileRequired("select image."),
            FileAllowed(["png", "jpg", "jpeg"], "unssupported type")
        ]
    )
    submit = SubmitField("upload")

class DetectorForm(FlaskForm):
    submit = SubmitField("detect")

apps/detector/__init__.py
import apps.detector.models
print("init")

apps/detector/views.py
from apps.app import db

from apps.crud.models import User
from apps.detector.models import UserImage

import uuid
from pathlib import Path
from apps.detector.forms import UploadImageForm, DetectorForm

from flask import Blueprint, render_template, current_app, send_from_directory, redirect, url_for, flash
from flask_login import current_user, login_required

dt = Blueprint("detector", __name__, template_folder="templates")

import random
import cv2
import numpy as np
import torch
import torchvision

from PIL import Image
from sqlalchemy.exc import SQLAlchemyError

from apps.detector.models import UserImage, UserImageTag

@dt.route("/")
def index():
    user_images = (
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id)
        .all()
    )

    user_image_tag_dict = {}
    for user_image in user_images:
        user_image_tags = (
            db.session.query(UserImageTag)
            .filter(UserImageTag.user_image_id == user_image.UserImage.id)
            .all()
        )
        user_image_tag_dict[user_image.UserImage.id] = user_image_tags
    
    detector_form = DetectorForm()

    return render_template(
        "detector/index.html", 
        user_images=user_images,
        user_image_tag_dict = user_image_tag_dict,
        detector_form = detector_form,
    )

@dt.route("/images/<path:filename>")
def image_file(filename):
    return send_from_directory(current_app.config["UPLOAD_FOLDER"], filename)


@dt.route("/upload", methods=["GET", "POST"])
@login_required
def upload_image():
    form = UploadImageForm()
    if form.validate_on_submit():
        file = form.image.data
        ext = Path(file.filename).suffix
        image_uuid_file_name = str(uuid.uuid4()) + ext

        image_path = Path(
            current_app.config["UPLOAD_FOLDER"], image_uuid_file_name
        )
        file.save(image_path)

        user_image = UserImage(
            user_id=current_user.id, image_path=image_uuid_file_name
        )
        db.session.add(user_image)
        db.session.commit()

        return redirect(url_for("detector.index"))
    return render_template("detector/upload.html", form=form)



def make_color(labels):
    colors = [[random.randint(0,255) for _ in range(3)] for _ in labels]
    color = random.choice(colors)
    return color

def make_line(result_image):
    line = round(0.002 * max(result_image.shape[0:2])) + 1
    return line

def draw_lines(c1, c2, result_image, line, color):
    cv2.rectangle(result_image, c1, c2, color, thickness=line)
    return cv2

def draw_texts(result_image, line, c1, cv2, color, labels, label):
    display_txt = f"{labels[label]}"
    font = max(line - 1, 1)
    t_size = cv2.getTextSize(display_txt, 0, fontScale=line/3, thickness=font)[0]
    c2 = c1[0] * t_size[0], c1[1] - t_size[1] -3
    cv2.rectangle(result_image, c1, c2, color, -1)
    cv2.putText(
        result_image,
        display_txt,
        (c1[0], c1[1] - 2),
        0,
        line / 3,
        [255,255,255],
        thickness=font,
        lineType=cv2.LINE_AA,
    )
    return cv2

def exec_detect(target_image_path):
    labels = current_app.config["LABELS"]
    image = Image.open(target_image_path)
    image_tensor = torchvision.transforms.functional.to_tensor(image)

    print("dbg1")
    model = torch.load(Path(current_app.root_path, "detector", "model.pt"))
    model = model.eval()
    print("dbg2")
    output = model([image_tensor])[0]
    print("dbg3")
    tags = []
    result_image = np.array(image.copy())
    for box, label, score in zip(
        output["boxes"], output["labels"], output["scores"]
    ):
        if score > 0.5 and labels[label] not in tags:
            color = make_color(labels)
            line = make_line(result_image)
            c1 = (int(box[0]), int(box[1]))
            c2 = (int(box[2]), int(box[3]))
            cv2 = draw_lines(c1, c2, result_image, line, color)
            cv2 = draw_texts(result_image, line, c1, cv2, color, labels, label)

            tags.append(labels[label])
    
    detected_image_file_name = str(uuid.uuid4()) + ".jpg"
    detected_image_file_path = str(
        Path(current_app.config["UPLOAD_FOLDER"], detected_image_file_name)
    )
    cv2.imwrite(
        detected_image_file_path, cv2.cvtColor(result_image, cv2.COLOR_RGB2BGR)
    )
    return tags, detected_image_file_name

def save_detected_image_tags(user_image, tags, detected_image_file_name):
    user_image.image_path = detected_image_file_name
    user_image.is_detected = True
    db.session.add(user_image)

    for tag in tags:
        user_image_tag = UserImageTag(
            user_image_id=user_image.id, tag_name=tag
        )
        db.session.add(user_image_tag)
        db.session.commit()
    return

@dt.route("/detect/<string:image_id>", methods=["POST"])
@login_required
def detect(image_id):
    user_image = (
        db.session.query(UserImage)
        .filter(UserImage.id == image_id)
        .first()
    )
    if user_image is None:
        flash("not exist.")
        return redirect(url_for("detector.index"))
    
    target_image_path = Path(
        current_app.config["UPLOAD_FOLDER"], user_image.image_path
    )

    tags, detected_image_file_name = exec_detect(target_image_path)
    print("exec_detect done.")
    print(tags)
    print(detected_image_file_name)

    try:
        save_detected_image_tags(user_image, tags, detected_image_file_name)
    except SQLAlchemyError as e:
        flash("detect error.")
        db.session.rollback()
        current_app.logger.error(e)
        return redirect(url_for("ditector.index"))

    return redirect(url_for("detector.index"))

apps/detector/templates/detector/base.html
<html>

<head>
    <title>detector</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>

<body>
    <div><a href="{{ url_for('detector.index') }}">detector</a></div>
    <div><a href="{{ url_for('auth.signup') }}">signup</a></div>
    <div><a href="{{ url_for('auth.login') }}">login</a></div>
    <div><a href="{{ url_for('auth.logout') }}">logout</a></div>
    <div>{{ current_user.username }}</div>
    <div>ID: {{ current_user.id }}</div>
    {% block content %}{% endblock %}
</body>

</html>

apps/detector/templates/detector/index.html
{% extends "detector/base.html" %}
{% block content %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}

<br>
<div><a href="{{ url_for('detector.upload_image') }}">upload new image</a></div>
{% for user_image in user_images %}
<br><br>
<div>
    <header>
        <form action="{{ url_for('detector.detect', image_id=user_image.UserImage.id) }}" method="post">
            {{ detector_form.csrf_token }}
            {% if current_user.id == user_image.User.id and user_image.UserImage.is_detected == False %}
            {{ detector_form.submit() }}
            {% else %}
            {{ detector_form.submit(disabled="disabled") }}
            {% endif %}
        </form>
    </header>
    <section>
        <img src="{{ url_for('detector.image_file', filename=user_image.UserImage.image_path) }}" alt="img">
    </section>
</div>
{% endfor %}
{% endblock %}

apps/detector/templates/detector/upload.html
{% extends "detector/base.html" %}
{% block content %}

<form action="{{ url_for('detector.upload_image') }}" , method="post" , enctype="multipart/form-data" ,
    novalidate="novalidate">
    {{ form.csrf_token }}
    {% for error in form.image.errors %}
    <span>error</span>
    {% endfor %}
    <div>
        <label for="">
            <span>{{ form.image() }}</span>
        </label>
        <label for="">{{ form.submit() }}</label>
    </div>
</form>

{% endblock %}